# fly.toml file generated for ai1-twitter-chatgpt on 2023-01-01T16:22:09-06:00

app = "ai1-twitter-chatgpt"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

